apiVersion: apps/v1
kind: Deployment
metadata:
  name: missing-scheduler-labels
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      schedulerName: rabbit-scheduler
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: with-scheduler-labels
  labels:
    app: nginx
    rabbitCompatible: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      schedulerName: rabbit-scheduler
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80