apiVersion: v1
kind: Pod
metadata:
  name: without-labels
  labels:
    role: myrole
spec:
  schedulerName: rabbit-scheduler
  containers:
    - name: web
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: with-labels
  labels:
    rabbitcompabitle: true
spec:
  schedulerName: rabbit-scheduler
  containers:
    - name: web
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP